# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "3072"
  end

  config.vm.provision :docker

  config.vm.define "server-1" do |ci|
    ci.vm.network "private_network", ip: '192.168.56.60'
    ci.vm.hostname = "ciserver"
    ci.vm.provision :file, source:"../docker/docker-compose.ci.yml", destination:"docker-compose.yml"
    ci.vm.provision :docker_compose, yml:"/home/vagrant/docker-compose.yml", run: "always"
    ci.vm.provision :shell, inline: "sudo chmod 777 /var/run/docker.sock"
  end
end